var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/generate-certificate/route.js")
R.c("server/chunks/node_modules_next_da17d727._.js")
R.c("server/chunks/node_modules_pdf-lib_es_core_1c65b47f._.js")
R.c("server/chunks/node_modules_pdf-lib_es_api_9cdcbbc9._.js")
R.c("server/chunks/node_modules_pdf-lib_es_634d7e73._.js")
R.c("server/chunks/node_modules_bb6b9e27._.js")
R.c("server/chunks/node_modules_@pdf-lib_standard-fonts_es_0e490e76._.js")
R.c("server/chunks/node_modules_18c9ae2a._.js")
R.c("server/chunks/[root-of-the-server]__ac05ded1._.js")
R.m("[project]/.next-internal/server/app/api/generate-certificate/route/actions.js [app-rsc] (server actions loader, ecmascript)")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/generate-certificate/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/generate-certificate/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
