var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/generate-certificate/route.js")
R.c("server/chunks/08db3_next_d382f530._.js")
R.c("server/chunks/08db3_pdf-lib_es_core_a57f2e68._.js")
R.c("server/chunks/08db3_pdf-lib_es_api_0b60df43._.js")
R.c("server/chunks/08db3_pdf-lib_es_6e47f31f._.js")
R.c("server/chunks/08db3_06054056._.js")
R.c("server/chunks/08db3_@pdf-lib_standard-fonts_es_4e04efb9._.js")
R.c("server/chunks/08db3_b561c98e._.js")
R.c("server/chunks/[root-of-the-server]__9236c1b5._.js")
R.m("[project]/quiz-app/.next-internal/server/app/api/generate-certificate/route/actions.js [app-rsc] (server actions loader, ecmascript)")
R.m("[project]/quiz-app/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/quiz-app/src/app/api/generate-certificate/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/quiz-app/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/quiz-app/src/app/api/generate-certificate/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
